### ISSUE TITLE
Treats all strings as the string `<string>`

### ISSUE THREAD

**Issue by raphinesse** [IndigoUnited/node-diff-json-structure#19]
```js
const diff = require('diff-json-structure')
const delta = diff(['foo'], ['bar'])
console.log(require('util').inspect(delta, { depth: null }))
```

Running the above code, logs this to the console
```js
[ { value: '[\n  "<string>"\n]', count: 3 } ]
```

If I just use `diff.diffJson` directly, everything works as intended:
```js
[ { count: 1, value: '[\n' },
  { count: 1, added: undefined, removed: true, value: '  "foo"\n' },
  { count: 1, added: true, removed: undefined, value: '  "bar"\n' },
  { count: 1, value: ']' } ]

```

**Comment by satazor** [comment]
Hello @raphinesse. Could you take some time to pinpoint the problem? My time is very scarse and it would be really helpful if you could diagnose the problem.

Thanks.

**Comment by raphinesse** [comment]
As I said, if you call `diff.diffJson` directly, everything works fine, so the problem seems to be caused by 
 `mapToType`. I already took a look at it but didn't see what's wrong nor what it's supposed to do in the first place.

**Comment by raphinesse** [comment]
Or is this tool actually supposed to only compare types?

**Comment by satazor** [comment]
@raphinesse yes that right, it diffs new items, deleted items or changes in item types. If that's not clear in the readme, perhaps it should be more clearer.

**Comment by raphinesse** [comment]
I just now noticed, that the examples only have types compared, too. I actually thought this was a "normal" object diff tool. So yes, I think it would be helpful to clarify the goal/intent of this tool in a sentence or two at the beginning of the Readme.

Sorry for bothering you and thanks for taking your time to reply.
